# MySQL Database Configuration (override via environment variables)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cookingdb?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cognito configuration
security.cognito.region=${COGNITO_REGION:ap-southeast-2}
security.cognito.user-pool-id=${COGNITO_USER_POOL_ID:ap-southeast-2_iesyw1kMl}
security.cognito.app-client-id=${COGNITO_APP_CLIENT_ID:2v36scmicr5rqoqio57g4hnqcv}
security.cognito.app-client-secret=${COGNITO_APP_CLIENT_SECRET:}

